### PR TITLE
Update miscellaneous.py

### PR DESCRIPTION
**Pull request by GDWR**
Reword the Zen of Python title to make more sense.

### CODE REVIEW

**Review by brad90four — APPROVED** [review]
Fastest LGTM in the server

**Review by dawnofmidnight — APPROVED** [review]
Top notch change. Absolutely exemplar work, Griff.

**Comment by KeithTheEE** [comment]
Looks good to me. Not quite as quickly as the server demands, but it'll do.

**Review by vivekashok1221 — APPROVED** [review]
:+1:

**Review by Xithrius — APPROVED** [review]

**Pull request merged**
