### PR TITLE
Weigh team chosen for team game towards those with fewer points.

### PR DESCRIPTION
**Pull request by swfarnsworth**
@hedyhli thought people would stay engaged if the game makes it easier for teams to catch up, so this PR introduces inverse weighting for which team has the opportunity to score points, based on the current scoreboard.

This log output indicates that the algorithm is correct:
```
 scores = {'list': 0, 'dict': 0, 'tuple': 5}, weights = [0.1923076923076923, 0.1923076923076923, 0.0384615384615
38464]
```
That is, list and dict are both weighted as more likely to be selected, since they have fewer points than tuple.

### CODE REVIEW

**Review by thurisatic — APPROVED** [review]
One of the many original idea suggested for this - to bias the team assignment for higher competitiveness - i am convinced cannot be done fairly. This method, however, where the reactions are biased instead, i think works just fine. It should be self-correcting regardless of join behavior, and it also helps if a significant number of one team is not present (asleep, for example)

I could make a team-patriotic change request to swap the lists to tuples, though 🤣

**Comment by thurisatic** [comment]
At roughly this time, with scores of 1700/1586/1201, it should switch probabilities to approximately 28.7%, 30.7%, and 40.6%, respectively, from equal ~33%

**Review by hedyhli — APPROVED** [review]
thanks for implementing this :)

:shipit:

**Review by Xithrius — APPROVED** [review]
I trust your math

**Pull request merged**
